name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
    - name: Test
      run: go test ./functions/...
    - name: Build
      run: go build -o output/oauth-debugger cmd/server/main.go
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: oauth-debugger
        path: output/oauth-debugger
